// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Env vars take precedence; the hardcoded fallbacks keep the build working
// when the environment has not been configured yet.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Required for Supabase confirmation and recovery URLs.  Keeping this
    // explicit prevents a future client-option change from silently sending
    // users back to the landing page without creating a session.
    detectSessionInUrl: true,
  }
});
